version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - gitlfs-{{ .Branch }}
            - gitlfs-master
      - run:
          name: Install rsync && Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get update
            apt-get install -y git-lfs rsync
            git lfs install
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
            git lfs pull

      - save_cache:
          key: gitlfs-{{ .Branch }}
          paths:
            - .git/lfs

      - deploy:
          name: Deploy via ssh
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            { ssh-keyscan $SSH_HOST 2> /dev/null; } >> ~/.ssh/known_hosts
            pwd
            ls
            if [ ${CIRCLE_BRANCH} = "master" ];then
                rsync -az -v --delete -e ssh /home/circleci/project/* $SSH_USER@$SSH_HOST:/var/www/www/sandbox/
            else
                echo "Not master branch"
            fi
